project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/deven367/clean_plot"
      - icon: twitter
        href: https://twitter.com/deven367
        aria-label: deven367 Twitter
  sidebar:
    style: floating
    collapse-level: 1
  favicon: favicon.png

metadata-files: [nbdev.yml, sidebar.yml]