package:
  name: clean_plot
  version: 0.0.1
source:
  sha256: 91cec463470b6919f652331ddd2a2a964ea516af9c240615a04fbeee799beea6
  url: https://files.pythonhosted.org/packages/4d/dd/f3147c52dd7950682145ab2857857104c6d4968f21131ed279fb37482e93/clean_plot-0.0.1.tar.gz
about:
  dev_url: https://deven367.github.io
  doc_url: https://deven367.github.io
  home: https://deven367.github.io
  license: Apache Software
  license_family: APACHE
  summary: This is a dummy project
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - deven367
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - clean_plot
