package:
  name: clean_plot
  version: 0.0.7
source:
  sha256: e89df652f177d681543cacfa056a38bdef6501fdc0080aed1c4fda71541e4db6
  url: https://files.pythonhosted.org/packages/06/d0/8074b43bf2b96cf7a072bf38e61513829d25a2f46790ec8a3fe76edcd1eb/clean_plot-0.0.7.tar.gz
about:
  dev_url: https://deven367.github.io
  doc_url: https://deven367.github.io
  home: https://deven367.github.io
  license: Apache Software
  license_family: APACHE
  summary: This is a dummy project
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - deven367
requirements:
  host:
  - pip
  - python
  - packaging
  - numpy
  - pandas
  - seaborn
  - sklearn
  - nltk
  - unidecode
  run:
  - pip
  - python
  - packaging
  - numpy
  - pandas
  - seaborn
  - sklearn
  - nltk
  - unidecode
test:
  imports:
  - clean_plot
